### ISSUE TITLE
Keymap coincidence

### ISSUE THREAD

**Issue by cristianvasquez** [MichalBures/obsidian-file-path-to-uri#1]
Nothing terrible, but your plugin uses the same (Ctrl/Cmd + Alt + L) key as the prettifier plugin :D

**Comment by MichalBures** [comment]
That's an unlucky coincidence :(

I've added a simple guide to the readme to show how you can change the hotkey if you need to:  https://github.com/MichalBures/obsidian-file-path-to-uri#how-to-change-the-hotkey-in-a-hacky-way

Hopefully Obsidian will provide some easy way to manage hotkeys soon.

**Comment by cristianvasquez** [comment]
Perhaps plugins should not assign default hotkeys, I'm not sure :)

**Comment by MichalBures** [comment]
Apparently I'm a goofball who can't read :D 

There is an option in the Obsidian settings to change the hotkeys for any command including this plugin. I've updated the readme yet again https://github.com/MichalBures/obsidian-file-path-to-uri#how-to-change-the-hotkey

Thank you for making me look into this!
