### ISSUE TITLE
Add command to insert current file URI

### ISSUE THREAD

**Issue by brimwats1** [MichalBures/obsidian-file-path-to-uri#3]
The current command can only be used if the file URI is typed out. Can a command be added that will insert the file URI so it can be toggled?

**Comment by MichalBures** [comment]
I'm not sure what you mean by inserting the URI. What URI and from where? Could you give me an example of what you are trying to achieve?

Just fyi on Windows if you Shift + Right click on a folder or a file there is "Copy as path" in the context menu that will copy the full path to a clipboard. Which you can then paste into Obsidian and toggle into file uri.

**Comment by brimwats1** [comment]
Exactly what you've said there! A command to insert the path of the current file. I want to then use the extension to toggle it to a URI and then I can copy and paste it into my task manager so it can be clicked. Does that make sense?

**Comment by MichalBures** [comment]
Chm, you mean the path of the currently opened file in Obsidian?

Say your Obsidian vault is in `C\:Obsidian` and you are using Obsidian to edit a file `todo.md` that's in the vault's root folder. You then want a command that would insert the file path `C:\Obsidian\todo.md`?

**Comment by brimwats1** [comment]
Yes that's what I was hoping—or perhaps something to "insert current file's URI" — that would skip the toggling step. If it's too much of a hassle don't feel obliged! Just was trying to figure out how to make it easier with keyboard commands

**Comment by MichalBures** [comment]
I'll have to look if the Obsidian API has this ability. If it does then it should be easy.

But I'm still curious as why do you need this? Is the ``[[]]`` link syntax not enough or are you linking to the file from another Vault or app?

**Comment by brimwats1** [comment]
> But I'm still curious as why do you need this? Is the `[[]]` link syntax not enough or are you linking to the file from another Vault or app?


I want to link directly to files in my task manager, Amazing Marvin, so I can say like 

* Work on [[Call for Papers]]  (with the URI). Then I can click on it and go directly to it in obsidian. Does that make sense? :)

**Comment by MichalBures** [comment]
Yes, now I understand, thank you for your patience :)

I believe the built-in command "Copy obsidian url" could be exactly what you're looking for?

**Comment by brimwats1** [comment]
It is! I didn't even know that was there. Sorry for all this nonsense then 🙈
