### ISSUE TITLE
Update if I move or change name of a file

### ISSUE THREAD

**Issue by AMGMNPLK** [MichalBures/obsidian-file-path-to-uri#5]
As with notes, if I change the name of the file or move it, it would be great if this plugin update that URL. I guess that a good way to do it is by checking when obsidian is running and also when it is started. In this last case, if the file has been moved an ideal solution would search in the computer to find files with the same name or/and creation date and modification dates. In case there would be more than one, ask the user.

With these options, this plugin would deserve to be official.

**Comment by MichalBures** [comment]
You have a good idea but it's way out of scope of this plugin.

It's certainly possible though. You'd have to either mark all the external links or just search all 'file:///*' links in your vault. And then periodically check if they exist and if they don't then show the link in red or something.
