### ISSUE TITLE
bug: missing "\" symbol

### ISSUE THREAD

**Issue by yejinson** [MichalBures/obsidian-file-path-to-uri#9]
<img src='https://s2.loli.net/2022/10/20/mGDVFJAbU5qrvWI.png' title='quicker_5c526f85-65bd-4eb0-bff0-3ef0fcceb3a8.png' />

**Comment by Karob2** [comment]
In makeLink in main.js or main.ts, I fixed this locally by appending to `title.replace(new RegExp('%20', 'g'), ' ')`, replacing it with `title.replace(new RegExp('%20', 'g'), ' ').replace(new RegExp('\\\\', 'g'), '\\\\')`.

**Comment by yejinson** [comment]
> In makeLink in main.js or main.ts, I fixed this locally by appending to `title.replace(new RegExp('%20', 'g'), ' ')`, replacing it with `title.replace(new RegExp('%20', 'g'), ' ').replace(new RegExp('\\\\', 'g'), '\\\\')`.

It works now, thank you very much.
